### PR TITLE
Fix AutoAttackRange on Orbwalk and Drawing

### PR DESCRIPTION
**Pull request by krankkkk**
Fixed changing AA-Range on Champions with Items/Level on Orbwalk and Drawing
Ignore the formatting changes, that is Visual Studio refusing to use the file as-Is

### CODE REVIEW

**Comment by emicovi** [comment]
> Fixed changing AA-Range on Champions with Items/Level on Orbwalk and Drawing
> Ignore the formatting changes, that is Visual Studio refusing to use the file as-Is

can you add me on discord please?

emicovi#1264

**Comment by Billybishop** [comment]
Thanks for the pull request Krank, i'll take a look when I get a chance and try to merge it

**Comment by safasetop** [comment]
Anyone, does anyone have an 11.8 offset? plz give me 

my discord 
Deleted User 61h94fen#1234

**Comment by qvimxyz** [comment]
> 
> 
> Thanks for the pull request Krank, i'll take a look when I get a chance and try to merge it

i'm having a issue if you could create the issue tab would be appreciate

**Comment by Konasiewicz** [comment]
when boosting got this problem ... any idea what to do ?

**Pull request closed without merging**
