### PR TITLE
nothing

### PR DESCRIPTION
**Pull request by Teals53**
nothing

### CODE REVIEW

**Comment by emicovi** [comment]
Billybishop can you add me on discord?  emicovi#1264

**Comment by Teals53** [comment]
also i found smthng can useful on some forums

image

(yes i know what is it exactly with story no need to say)

**Comment by Lem4aks** [comment]
Can give this me?

**Comment by Teals53** [comment]
> Can give this me?
> 
> 

Teals53#1508

**Comment by Teals53** [comment]
also can u add a bar for xp track ?

**Comment by Teals53** [comment]
this new base have lot of stuff but need some core improvoments can u make ?

**Comment by Teals53** [comment]
@Billybishop can you add me on discord pls

Teals53#1508

**Comment by Billybishop** [comment]
sorry, i wasn't getting notifications for github for some reason, i'll merge these changes and catch up with the comments now.

here is my discord as well: TRACASSEUR#4592

**Comment by Billybishop** [comment]
Ok so I reviewed most of these scripts and I'm still not sure what "Blitz" is referring to. Is Blitz an older platform that these are ported from? I think we can merge most of these, but I'd like to move away from the existing formatting and naming structure - i'll move the EvadeUtils into commons and I diffed skills and targeting modules and they're outdated so I won't merge those, but do you know if there is anything meaningful needed to be merged from orbwalker.py?

**Comment by Teals53** [comment]
> Tamam, bu yüzden bu komut dosyalarının çoğunu inceledim ve "Blitz" in neyi kastettiğinden hala emin değilim. Blitz, bunların aktarıldığı daha eski bir platform mu? Bunların çoğunu birleştirebileceğimizi düşünüyorum, ancak mevcut biçimlendirme ve adlandırma yapısından uzaklaşmak istiyorum - EvadeUtils'i ortak kullanıma taşıyacağım ve farklı beceriler ve hedefleme modülleri ve modası geçmişler, bu yüzden yapmayacağım bunları birleştirin, ancak orbwalker.py'den birleştirilmesi gereken anlamlı bir şey olup olmadığını biliyor musunuz?

maybe someone taked lview and renamed that then tried to sell idk it doesnt matter bro change whatever u want if something is usefull also they have more skills can be merge right ? for orbwalks idk maybe isTargetable stuff or atkRange im not talented as much like u bro

**Comment by Billybishop** [comment]
Sorry for prematurely closing this, but it appears that some of the scripts here are copied from another project, so in order to respect that I have closed the request and if you want to discuss this decision please pm me on UC or on discord. Thanks.

**Pull request closed without merging**
